version: '2.4'

services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: kong:2.0
    stop_signal: SIGTERM
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KONG_LOG_LEVEL=info
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_ACCESS_LOG=off
      - KONG_PROXY_ACCESS_LOG=off
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_PORT=5432
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PLUGINS=bundled,upstream-basic-auth
    entrypoint: 
      - /bin/sh
      - -c
      - luarocks install --local kong-plugin-upstream-basic-auth; kong migrations bootstrap ; kong migrations up && kong migrations finish
    restart: on-failure

  kong:
    image: kong:2.0
    stop_signal: SIGTERM
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 6
    environment:
      - KONG_LOG_LEVEL=info
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_ACCESS_LOG=off
      - KONG_PROXY_ACCESS_LOG=off
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_PORT=5432
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PLUGINS=bundled,upstream-basic-auth
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    entrypoint: 
      - /bin/sh
      - -c
      - luarocks install --local kong-plugin-upstream-basic-auth && exec /docker-entrypoint.sh kong docker-start
    restart: on-failure
